### ISSUE TITLE
openy_editor_update_8005 fails

### ISSUE THREAD

**Issue by froboy** [open-y-subprojects/openy_features#55]
When I pulled https://github.com/open-y-subprojects/openy_features/pull/49/files#diff-17256689995c9a6608df336326eae5fb6b89d61aebbec87b7ec8d15a08d8715aR80-R81 into my codebase and ran `drush updb` the update failed with:

>  [error]  array_splice(): Argument #1 ($array) must be of type array, null given 

It looks like my config looks different than this is expecting:
<img width="328" alt="Cursor_and_openy-dev_–_openy_editor_install__openy-dev_" src="https://github.com/open-y-subprojects/openy_features/assets/238201/25d7bbce-224a-47bd-8a51-6bba73175407">

and from my config export `editor.editor.full_html.yml` :

```
settings:
  toolbar:
    rows:
      -
        -
          name: Formatting
          items:
            - Bold
            - Italic
            - ...
```
